[package]
name = "gdext-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
real_is_double = []
formatted = ["gdext-codegen/formatted"]

[build-dependencies]
bindgen = "0.59"
gdext-codegen = { path = "../gdext-codegen" }
